#!/usr/bin/env bash

# Aliases
## Common
alias \
	sudo='sudo ' \
	df='df -h' \
	cp='cp -i' \
	mv='mv -i' \
	rm='rm -i' \
	grep='grep -i --color' \
	ls="ls -hN --color=auto --group-directories-first"

## App Specific
alias \
	vi=nvim \
	ws=".config/styli.sh/styli.sh -l reddit" \
	# alias ls='ls -hF --color' \
	jrnl='journalctl -p 3 -xb' \
	# r='ranger' \
	# alias w='nitrogen --set-zoom-fill --random ~/Pictures/wallpapers' \
	colors='for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$"\n"}; done'

## Pacman
alias \
	search='pacman -Ss' \
	# info='pacman -Q --info' \
	info='pacman -Qq ' \
	autoclean='pacman -Qdtq | sudo pacman -Rc -' \
	pac='sudo pacman'

## Dotfile
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

## Git
alias \
	glog='git log --pretty=oneline --abbrev-commit' \
	glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold green)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold yellow)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all" \
	commit='git commit -S -m' \
	checkout='git checkout' \
	push='git push' \
	pull='git pull' \
	status='git status'

## Misc
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
